### ISSUE TITLE
Will this work with shells besides Fish?

### ISSUE THREAD

**Issue by poperigby** [bool3max/bote#1]
This script looks really cool, but I use zsh.

**Comment by bool3max** [comment]
You don't need to switch your shell, just install `fish` and this script will run appropriately. 

(the first line of the script, `#!/usr/bin/fish` tells it to use execute the script using fish when you run it), the shell you use in your terminal doesn't matter :)

**Comment by poperigby** [comment]
Oh right, thanks (:
